// Code generated by protoc-gen-go. DO NOT EDIT.
// source: streaming.proto

package streaming

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PONG_NUM int32

const (
	PONG_NUM_EMPTY PONG_NUM = 0
	PONG_NUM_PING  PONG_NUM = 1
	PONG_NUM_PONG  PONG_NUM = 2
)

var PONG_NUM_name = map[int32]string{
	0: "EMPTY",
	1: "PING",
	2: "PONG",
}

var PONG_NUM_value = map[string]int32{
	"EMPTY": 0,
	"PING":  1,
	"PONG":  2,
}

func (x PONG_NUM) String() string {
	return proto.EnumName(PONG_NUM_name, int32(x))
}

func (PONG_NUM) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f2e8ceba11142904, []int{0}
}

type ClientMsg struct {
	Timestamp *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Event:
	//	*ClientMsg_ClnSendPingPong
	//	*ClientMsg_ClnShutdown_
	Event                isClientMsg_Event `protobuf_oneof:"event"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ClientMsg) Reset()         { *m = ClientMsg{} }
func (m *ClientMsg) String() string { return proto.CompactTextString(m) }
func (*ClientMsg) ProtoMessage()    {}
func (*ClientMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2e8ceba11142904, []int{0}
}

func (m *ClientMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientMsg.Unmarshal(m, b)
}
func (m *ClientMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientMsg.Marshal(b, m, deterministic)
}
func (m *ClientMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientMsg.Merge(m, src)
}
func (m *ClientMsg) XXX_Size() int {
	return xxx_messageInfo_ClientMsg.Size(m)
}
func (m *ClientMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ClientMsg proto.InternalMessageInfo

func (m *ClientMsg) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type isClientMsg_Event interface {
	isClientMsg_Event()
}

type ClientMsg_ClnSendPingPong struct {
	ClnSendPingPong *SendPingPong `protobuf:"bytes,2,opt,name=cln_send_ping_pong,json=clnSendPingPong,proto3,oneof"`
}

type ClientMsg_ClnShutdown_ struct {
	ClnShutdown *ClientMsg_ClnShutdown `protobuf:"bytes,3,opt,name=cln_shutdown,json=clnShutdown,proto3,oneof"`
}

func (*ClientMsg_ClnSendPingPong) isClientMsg_Event() {}

func (*ClientMsg_ClnShutdown_) isClientMsg_Event() {}

func (m *ClientMsg) GetEvent() isClientMsg_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *ClientMsg) GetClnSendPingPong() *SendPingPong {
	if x, ok := m.GetEvent().(*ClientMsg_ClnSendPingPong); ok {
		return x.ClnSendPingPong
	}
	return nil
}

func (m *ClientMsg) GetClnShutdown() *ClientMsg_ClnShutdown {
	if x, ok := m.GetEvent().(*ClientMsg_ClnShutdown_); ok {
		return x.ClnShutdown
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ClientMsg) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ClientMsg_ClnSendPingPong)(nil),
		(*ClientMsg_ClnShutdown_)(nil),
	}
}

type ClientMsg_ClnShutdown struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientMsg_ClnShutdown) Reset()         { *m = ClientMsg_ClnShutdown{} }
func (m *ClientMsg_ClnShutdown) String() string { return proto.CompactTextString(m) }
func (*ClientMsg_ClnShutdown) ProtoMessage()    {}
func (*ClientMsg_ClnShutdown) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2e8ceba11142904, []int{0, 0}
}

func (m *ClientMsg_ClnShutdown) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientMsg_ClnShutdown.Unmarshal(m, b)
}
func (m *ClientMsg_ClnShutdown) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientMsg_ClnShutdown.Marshal(b, m, deterministic)
}
func (m *ClientMsg_ClnShutdown) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientMsg_ClnShutdown.Merge(m, src)
}
func (m *ClientMsg_ClnShutdown) XXX_Size() int {
	return xxx_messageInfo_ClientMsg_ClnShutdown.Size(m)
}
func (m *ClientMsg_ClnShutdown) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientMsg_ClnShutdown.DiscardUnknown(m)
}

var xxx_messageInfo_ClientMsg_ClnShutdown proto.InternalMessageInfo

type ServerMsg struct {
	Timestamp *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Event:
	//	*ServerMsg_SrvSendPingPong
	//	*ServerMsg_SrvShutdown_
	Event                isServerMsg_Event `protobuf_oneof:"event"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ServerMsg) Reset()         { *m = ServerMsg{} }
func (m *ServerMsg) String() string { return proto.CompactTextString(m) }
func (*ServerMsg) ProtoMessage()    {}
func (*ServerMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2e8ceba11142904, []int{1}
}

func (m *ServerMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerMsg.Unmarshal(m, b)
}
func (m *ServerMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerMsg.Marshal(b, m, deterministic)
}
func (m *ServerMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerMsg.Merge(m, src)
}
func (m *ServerMsg) XXX_Size() int {
	return xxx_messageInfo_ServerMsg.Size(m)
}
func (m *ServerMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ServerMsg proto.InternalMessageInfo

func (m *ServerMsg) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type isServerMsg_Event interface {
	isServerMsg_Event()
}

type ServerMsg_SrvSendPingPong struct {
	SrvSendPingPong *SendPingPong `protobuf:"bytes,2,opt,name=srv_send_ping_pong,json=srvSendPingPong,proto3,oneof"`
}

type ServerMsg_SrvShutdown_ struct {
	SrvShutdown *ServerMsg_SrvShutdown `protobuf:"bytes,3,opt,name=srv_shutdown,json=srvShutdown,proto3,oneof"`
}

func (*ServerMsg_SrvSendPingPong) isServerMsg_Event() {}

func (*ServerMsg_SrvShutdown_) isServerMsg_Event() {}

func (m *ServerMsg) GetEvent() isServerMsg_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *ServerMsg) GetSrvSendPingPong() *SendPingPong {
	if x, ok := m.GetEvent().(*ServerMsg_SrvSendPingPong); ok {
		return x.SrvSendPingPong
	}
	return nil
}

func (m *ServerMsg) GetSrvShutdown() *ServerMsg_SrvShutdown {
	if x, ok := m.GetEvent().(*ServerMsg_SrvShutdown_); ok {
		return x.SrvShutdown
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ServerMsg) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ServerMsg_SrvSendPingPong)(nil),
		(*ServerMsg_SrvShutdown_)(nil),
	}
}

type ServerMsg_SrvShutdown struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerMsg_SrvShutdown) Reset()         { *m = ServerMsg_SrvShutdown{} }
func (m *ServerMsg_SrvShutdown) String() string { return proto.CompactTextString(m) }
func (*ServerMsg_SrvShutdown) ProtoMessage()    {}
func (*ServerMsg_SrvShutdown) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2e8ceba11142904, []int{1, 0}
}

func (m *ServerMsg_SrvShutdown) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerMsg_SrvShutdown.Unmarshal(m, b)
}
func (m *ServerMsg_SrvShutdown) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerMsg_SrvShutdown.Marshal(b, m, deterministic)
}
func (m *ServerMsg_SrvShutdown) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerMsg_SrvShutdown.Merge(m, src)
}
func (m *ServerMsg_SrvShutdown) XXX_Size() int {
	return xxx_messageInfo_ServerMsg_SrvShutdown.Size(m)
}
func (m *ServerMsg_SrvShutdown) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerMsg_SrvShutdown.DiscardUnknown(m)
}

var xxx_messageInfo_ServerMsg_SrvShutdown proto.InternalMessageInfo

type SendPingPong struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Type                 PONG_NUM `protobuf:"varint,2,opt,name=type,proto3,enum=streaming.PONG_NUM" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendPingPong) Reset()         { *m = SendPingPong{} }
func (m *SendPingPong) String() string { return proto.CompactTextString(m) }
func (*SendPingPong) ProtoMessage()    {}
func (*SendPingPong) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2e8ceba11142904, []int{2}
}

func (m *SendPingPong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendPingPong.Unmarshal(m, b)
}
func (m *SendPingPong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendPingPong.Marshal(b, m, deterministic)
}
func (m *SendPingPong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendPingPong.Merge(m, src)
}
func (m *SendPingPong) XXX_Size() int {
	return xxx_messageInfo_SendPingPong.Size(m)
}
func (m *SendPingPong) XXX_DiscardUnknown() {
	xxx_messageInfo_SendPingPong.DiscardUnknown(m)
}

var xxx_messageInfo_SendPingPong proto.InternalMessageInfo

func (m *SendPingPong) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *SendPingPong) GetType() PONG_NUM {
	if m != nil {
		return m.Type
	}
	return PONG_NUM_EMPTY
}

func init() {
	proto.RegisterEnum("streaming.PONG_NUM", PONG_NUM_name, PONG_NUM_value)
	proto.RegisterType((*ClientMsg)(nil), "streaming.ClientMsg")
	proto.RegisterType((*ClientMsg_ClnShutdown)(nil), "streaming.ClientMsg.ClnShutdown")
	proto.RegisterType((*ServerMsg)(nil), "streaming.ServerMsg")
	proto.RegisterType((*ServerMsg_SrvShutdown)(nil), "streaming.ServerMsg.SrvShutdown")
	proto.RegisterType((*SendPingPong)(nil), "streaming.SendPingPong")
}

func init() { proto.RegisterFile("streaming.proto", fileDescriptor_f2e8ceba11142904) }

var fileDescriptor_f2e8ceba11142904 = []byte{
	// 350 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x92, 0x4b, 0x4f, 0xc2, 0x40,
	0x10, 0xc7, 0x29, 0x2f, 0xe9, 0x80, 0xd2, 0xac, 0x24, 0x92, 0x5e, 0x24, 0x5c, 0x44, 0x0f, 0xc5,
	0xe0, 0xc5, 0x78, 0xd4, 0x20, 0x72, 0x00, 0x9b, 0x16, 0x0f, 0x9e, 0x1a, 0x1e, 0x6b, 0x25, 0xa1,
	0xdb, 0xa6, 0xbb, 0x60, 0xfc, 0xce, 0x7e, 0x08, 0x97, 0xc1, 0xb6, 0xab, 0xc1, 0x83, 0xf1, 0x36,
	0x8f, 0xff, 0xfc, 0x67, 0x7e, 0xd9, 0x85, 0x3a, 0x17, 0x31, 0x9d, 0x06, 0x4b, 0xe6, 0x5b, 0x51,
	0x1c, 0x8a, 0x90, 0xe8, 0x69, 0xc1, 0x3c, 0xf5, 0xc3, 0xd0, 0x5f, 0xd1, 0x2e, 0x36, 0x66, 0xeb,
	0x97, 0xae, 0x58, 0x06, 0x94, 0x8b, 0x69, 0x10, 0xed, 0xb4, 0xed, 0x0f, 0x0d, 0xf4, 0xbb, 0xd5,
	0x92, 0x32, 0x31, 0xe2, 0x3e, 0xb9, 0x06, 0x3d, 0x15, 0x34, 0xb5, 0x96, 0xd6, 0xa9, 0xf6, 0x4c,
	0x6b, 0x67, 0x61, 0x25, 0x16, 0xd6, 0x24, 0x51, 0x38, 0x99, 0x98, 0xdc, 0x03, 0x99, 0xaf, 0x98,
	0xc7, 0x29, 0x5b, 0x78, 0x91, 0xdc, 0xec, 0x45, 0x21, 0xf3, 0x9b, 0x79, 0xb4, 0x38, 0xb1, 0xb2,
	0x0b, 0x5d, 0x29, 0xb0, 0x65, 0x60, 0xcb, 0xf6, 0x43, 0xce, 0xa9, 0xcb, 0x21, 0xb5, 0x44, 0xfa,
	0x50, 0x43, 0x9f, 0xd7, 0xb5, 0x58, 0x84, 0x6f, 0xac, 0x59, 0x40, 0x87, 0x96, 0xe2, 0x90, 0x5e,
	0x2b, 0x23, 0xe6, 0x7e, 0xe9, 0xa4, 0x55, 0x75, 0x9e, 0xa5, 0xe6, 0x21, 0x54, 0x95, 0xee, 0xed,
	0x01, 0x94, 0xe8, 0x46, 0x4e, 0x21, 0xae, 0x4b, 0xe3, 0x0d, 0x8d, 0xff, 0x8d, 0xcb, 0xe3, 0xcd,
	0xdf, 0x71, 0xe5, 0xd0, 0x4f, 0x5c, 0xf4, 0xf9, 0x1d, 0x37, 0xbd, 0xd6, 0x72, 0xe5, 0xac, 0x82,
	0xcb, 0xb3, 0x74, 0x8b, 0xab, 0x74, 0x33, 0xdc, 0x21, 0xd4, 0xbe, 0xad, 0x33, 0xa0, 0x10, 0x70,
	0x1f, 0x51, 0x75, 0x67, 0x1b, 0x92, 0x33, 0x28, 0x8a, 0xf7, 0x88, 0xe2, 0xe9, 0x47, 0xbd, 0x63,
	0x65, 0xb1, 0xfd, 0x38, 0x1e, 0x78, 0xe3, 0xa7, 0x91, 0x83, 0x82, 0x8b, 0x73, 0xa8, 0x24, 0x15,
	0xa2, 0x43, 0xa9, 0x3f, 0xb2, 0x27, 0xcf, 0x46, 0x8e, 0x54, 0xa0, 0x68, 0x0f, 0xc7, 0x03, 0x43,
	0xc3, 0x48, 0x0a, 0x8c, 0x7c, 0x6f, 0x00, 0xd9, 0x0f, 0x24, 0x37, 0x50, 0x76, 0x31, 0x21, 0x8d,
	0x7d, 0x8f, 0x68, 0x36, 0xf6, 0xb1, 0xb6, 0x73, 0x1d, 0xed, 0x52, 0x9b, 0x95, 0xf1, 0x11, 0xae,
	0x3e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x7d, 0x05, 0xf5, 0x2f, 0xe2, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StreamingClient is the client API for Streaming service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StreamingClient interface {
	Stream(ctx context.Context, opts ...grpc.CallOption) (Streaming_StreamClient, error)
}

type streamingClient struct {
	cc *grpc.ClientConn
}

func NewStreamingClient(cc *grpc.ClientConn) StreamingClient {
	return &streamingClient{cc}
}

func (c *streamingClient) Stream(ctx context.Context, opts ...grpc.CallOption) (Streaming_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Streaming_serviceDesc.Streams[0], "/streaming.streaming/Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamingStreamClient{stream}
	return x, nil
}

type Streaming_StreamClient interface {
	Send(*ClientMsg) error
	Recv() (*ServerMsg, error)
	grpc.ClientStream
}

type streamingStreamClient struct {
	grpc.ClientStream
}

func (x *streamingStreamClient) Send(m *ClientMsg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *streamingStreamClient) Recv() (*ServerMsg, error) {
	m := new(ServerMsg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StreamingServer is the server API for Streaming service.
type StreamingServer interface {
	Stream(Streaming_StreamServer) error
}

// UnimplementedStreamingServer can be embedded to have forward compatible implementations.
type UnimplementedStreamingServer struct {
}

func (*UnimplementedStreamingServer) Stream(srv Streaming_StreamServer) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}

func RegisterStreamingServer(s *grpc.Server, srv StreamingServer) {
	s.RegisterService(&_Streaming_serviceDesc, srv)
}

func _Streaming_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamingServer).Stream(&streamingStreamServer{stream})
}

type Streaming_StreamServer interface {
	Send(*ServerMsg) error
	Recv() (*ClientMsg, error)
	grpc.ServerStream
}

type streamingStreamServer struct {
	grpc.ServerStream
}

func (x *streamingStreamServer) Send(m *ServerMsg) error {
	return x.ServerStream.SendMsg(m)
}

func (x *streamingStreamServer) Recv() (*ClientMsg, error) {
	m := new(ClientMsg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Streaming_serviceDesc = grpc.ServiceDesc{
	ServiceName: "streaming.streaming",
	HandlerType: (*StreamingServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _Streaming_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "streaming.proto",
}
